export default {
  'MENU_STATUS_REMOVE':'MENU_STATUS_REMOVE',
  'MENU_SUCCESS':'MENU_SUCCESS',
  'MENU_ERROR':'MENU_ERROR',
  'MENU_WARNING':'MENU_WARNING',
  'MENU_ITEM_SUCCESS':'MENU_ITEM_SUCCESS',
  'MENU_ITEM_ERROR':'MENU_ITEM_ERROR',
  'MENU_ITEM_WARNING':'MENU_ITEM_WARNING',
};